version: "3.8"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000 # This must match the UID you set on the host's /mnt/data-hdd
      - PGID=1000 # This must match the GID you set on the host's /mnt/data-hdd
      - TZ=Europe/Zurich # Your timezone
    volumes:
      - ./config/prowlarr:/config # Prowlarr's configuration
    ports:
      - 9696:9696 # Prowlarr web UI
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - ./config/radarr:/config
      - /data/media/movies:/movies # This maps to the /mnt/data-hdd/media/movies on host
      - /data/downloads:/downloads # This maps to the /mnt/data-hdd/downloads on host
    ports:
      - 7878:7878 # Radarr web UI
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - ./config/sonarr:/config
      - /data/media/tv:/tv # This maps to the /mnt/data-hdd/media/tv on host
      - /data/downloads:/downloads
    ports:
      - 8989:8989 # Sonarr web UI
    restart: unless-stopped

  # Add more services (Lidarr, Readarr, Whisparr) similarly
  # Remember to adjust ports, paths, and environment variables for each
  # Example Lidarr:
  # lidarr:
  #   image: lscr.io/linuxserver/lidarr:latest
  #   container_name: lidarr
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/Zurich
  #   volumes:
  #     - ./config/lidarr:/config
  #     - /data/media/music:/music
  #     - /data/downloads:/downloads
  #   ports:
  #     - 8686:8686
  #   restart: unless-stopped
