version: "3.8"
services:
  # Radarr is a movie collection manager for Usenet and BitTorrent users.
  # It automates the downloading, sorting, and renaming of movie files.
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - /etc/localtime:/etc/localtime:ro # Read-only access to host's timezone info
      - ./config/radarr:/config # Container's configuration files and database, now relative to docker-compose.yml
      - /data:/data # Main media library and download folders

  # Sonarr is a TV show collection manager for Usenet and BitTorrent users.
  # It automates the downloading, sorting, and renaming of TV show episodes.
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - /etc/localtime:/etc/localtime:ro # Read-only access to host's timezone info
      - ./config/sonarr:/config # Container's configuration files and database, now relative to docker-compose.yml
      - /data:/data # Main media library and download folders

  # Bazarr is a companion application to Radarr and Sonarr.
  # It manages and downloads subtitles for your movies and TV shows.
  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 6767:6767
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - /etc/localtime:/etc/localtime:ro # Read-only access to host's timezone info
      - ./config/bazarr:/config # Container's configuration files and database, now relative to docker-compose.yml
      - /data/media:/data/media # Media library for subtitle scanning (ensure this matches your final media location)

  # SABnzbd is an automated Usenet download client.
  # It downloads, verifies, repairs, and extracts files from Usenet.
  sabnzbd:
    container_name: sabnzbd
    image: ghcr.io/hotio/sabnzbd:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8080:8080
      - 9090:9090 # Only expose if needed for external API access
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - /etc/localtime:/etc/localtime:ro # Read-only access to host's timezone info
      - ./config/sabnzbd:/config # Container's configuration files and database, now relative to docker-compose.yml
      - /data/usenet:/data/usenet # Download directory for Usenet files

  # Prowlarr is an indexer manager/proxy for your *arr apps.
  # It centralizes management of Usenet indexers and Torrent trackers.
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 9696:9696 # Prowlarr web UI
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/prowl
